[package]
name = "rust-wasmer-app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasmer = "3.1"
anyhow = "1.0"
